KERNEL_ADDRESS = 0x7c00 + 512 + 512
STACK_ADDRESS = 0x7c00 - 1
IDT_ADDRESS = 0x0
IDT_ENTRIES = 256
IDTR_ADDRESS = IDT_ADDRESS + IDT_ENTRIES * 8
IDTR_SIZE = 6
MEM_MAP_ADDRESS = IDTR_ADDRESS + IDTR_SIZE
MEM_MAP_ENTRIES_START = MEM_MAP_ADDRESS + 4